language: php

php:
 - 7.1.3

services:
 - postgresql

before_script:
 #- psql -c 'create database test_db;' -U postgres
 - mysql -uroot -e "create database test_db;"
 - curl -s http://getcomposer.org/installer | php
 - php composer.phar install

script: vendor/bin/phpunit

notifications:
 webhooks: https://c2c57b5c.ngrok.io/notifications
  on_success: never
